<div class="row">
    <div class="col-sm">
    </div>
    <div class="table-responsive"> 
    <h1>ACTIVITIES.</h1>
    <table class="table table-striped table-light" style="color:gray;">

              <thead>
                <tr style="color:black;">
                  <th scope="col">No.</th>
                  <th scope="col">Activity</th>
                  <th scope="col">Date</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
              <?php
              $id=$this->session->get('memberAuthen');
              $act = Event::find("");
              for ($i=0;$i<count($act);$i++){?>
                <tr>
                  <th scope="row"><?php echo "$i"+1 ?></th>
                  <td><?php
                    echo $act[$i]->name; ?></td>
                  <td><?php echo $act[$i]->date; ?></td>
                  <td><a style="color:white;" href="<?php echo $this->url->getBaseUri(); ?>event/setId/<?php echo $act[$i]->id;?>" class="btn btn-info" id="edit<?php echo $act[$i]->id;?>" name="edit<?php echo $act[$i]->id;?>" value="<?php echo $act[$i]->id;?>">edit</a></td>
                  <td><a href="<?php echo $this->url->getBaseUri(); ?>event/deleteId/<?php echo $act[$i]->id;?>" class="btn btn-danger">delete</a></td>
                </tr>
              <?php }?>
              </tbody>
            </table>
          </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
  
  <a href="<?php echo $this->url->getBaseUri(); ?>add" class="btn btn-success">ADD</a>